//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIPO.Units
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public int Units { get; set; }
        public int ETA { get; set; }
        public System.DateTime DateCreation { get; set; }
        public bool IsInProduction { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<int> TimeInproduction { get; set; }
    }
}
