//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIPO.Units
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnitianXArea
    {
        public int Id { get; set; }
        public Nullable<int> IdArea { get; set; }
        public Nullable<int> Technitian { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Technitian Technitian1 { get; set; }
    }
}
