//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIPO.Units.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIPO.Units.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1483065445_play_circle_outline {
            get {
                object obj = ResourceManager.GetObject("1483065445_play-circle-outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1483065496_play_circle_outline {
            get {
                object obj = ResourceManager.GetObject("1483065496_play-circle-outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can&apos;t add more units to this case.
        /// </summary>
        internal static string CreateCases_ValidateCase_you_can_t_add_more_units_to_this_case {
            get {
                return ResourceManager.GetString("CreateCases_ValidateCase_you_can_t_add_more_units_to_this_case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case number Required!.
        /// </summary>
        internal static string CreateCases_ValidateCases_Case_number_Required {
            get {
                return ResourceManager.GetString("CreateCases_ValidateCases_Case_number_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time production required.
        /// </summary>
        internal static string CreateCases_ValidateCases_Time_production_required {
            get {
                return ResourceManager.GetString("CreateCases_ValidateCases_Time_production_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Required.
        /// </summary>
        internal static string CreateCases_ValidateCases_Units_Required {
            get {
                return ResourceManager.GetString("CreateCases_ValidateCases_Units_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case not created previously.
        /// </summary>
        internal static string ProductivityForm_CreateCase_Case_not_created_previously {
            get {
                return ResourceManager.GetString("ProductivityForm_CreateCase_Case_not_created_previously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string xHoursMaximun {
            get {
                return ResourceManager.GetString("xHoursMaximun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string xHoursMinimun {
            get {
                return ResourceManager.GetString("xHoursMinimun", resourceCulture);
            }
        }
    }
}
